name: Build Docker Image

on:
  push:
    paths:
      - 'Dockerfile'
      - '.github/workflows/build-docker.yml'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Convert repository name to lowercase
        id: repo
        run: echo "repo_lower=$(echo ${{ github.repository }} | tr '[:upper:]' '[:lower:]')" >> $GITHUB_OUTPUT
      
      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: |
            ghcr.io/${{ steps.repo.outputs.repo_lower }}/algorithm-runner:latest
            ghcr.io/${{ steps.repo.outputs.repo_lower }}/algorithm-runner:${{ github.sha }}