name: C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Build and Run inside Docker
      run: |
        docker build -t llm-cpp-env .
        docker run --rm llm-cpp-env bash -c "mkdir build && cd build && cmake .. && make && ./hello_world"